spring.application.name=Nursery Backend

# URL de la base de datos
spring.datasource.url = jdbc:postgresql://localhost:5432/nursery
spring.datasource.username = postgres
spring.datasource.password = postgres

# Driver postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.root=INFO

server.error.include-message=always
server.error.include-stacktrace=always
