spring.application.name=Nursery Backend

# URL de la base de datos
spring.datasource.url = jdbc:postgresql://localhost:5432/nursery
spring.datasource.username = postgres
spring.datasource.password = postgres

# Driver postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.root=INFO

server.error.include-message=always
server.error.include-stacktrace=always

# Para ver más detalles de la autenticación
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG

# JWT
jwt.secret=m1-sup3r-s3cr3t0-jwt-12345678901234567890
jwt.expiration=3600000